# Generated by Django 5.2.1 on 2025-05-20 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "med_code_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("term", models.CharField(max_length=500)),
                ("observations", models.BigIntegerField(blank=True, null=True)),
                ("snomed_ct_concept_id", models.CharField(blank=True, max_length=50)),
                ("emis_category", models.CharField(blank=True, max_length=100)),
                ("coding_system", models.CharField(blank=True, max_length=50)),
                ("is_negation", models.BooleanField(default=False)),
                ("is_familial", models.BooleanField(default=False)),
                ("is_screening", models.BooleanField(default=False)),
                ("is_referral", models.BooleanField(default=False)),
                ("is_suspected", models.BooleanField(default=False)),
                ("is_advice", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CodeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codelist_name", models.CharField(max_length=255)),
                ("project_title", models.CharField(blank=True, max_length=255)),
                ("ERAP_number", models.CharField(blank=True, max_length=50)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("codelist_description", models.TextField(blank=True)),
                (
                    "emis_dictionary_version",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CodeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CodeListCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_excluded", models.BooleanField(default=False)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.code"
                    ),
                ),
                (
                    "codelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.codelist"
                    ),
                ),
            ],
            options={"unique_together": {("code", "codelist")},},
        ),
        migrations.AddField(
            model_name="code",
            name="codelists",
            field=models.ManyToManyField(
                through="core.CodeListCode", to="core.codelist"
            ),
        ),
        migrations.AddField(
            model_name="codelist",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.codesource"
            ),
        ),
        migrations.CreateModel(
            name="UserCodeListSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "codelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.codelist"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCodeExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.code"
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usercodelistselection",
                    ),
                ),
            ],
            options={"unique_together": {("selection", "code")},},
        ),
    ]
