# Generated by Django 5.2.1 on 2025-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelist",
            name="clinical_domain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="codelist",
            name="code_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="codelist",
            name="last_validated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codelist",
            name="unique_identifier",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
