# Generated by Django 5.2.1 on 2025-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_unique_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmisCode",
            fields=[
                (
                    "med_code_id",
                    models.CharField(
                        help_text="Medical Code ID (may have 'a' prefix)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clean_med_code_id",
                    models.CharField(
                        db_index=True,
                        help_text="Code ID with 'a' prefix removed",
                        max_length=50,
                    ),
                ),
                (
                    "observations",
                    models.BigIntegerField(help_text="Number of observations in EMIS"),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="Medical term description", max_length=1000
                    ),
                ),
                (
                    "snomed_ct_concept_id",
                    models.CharField(
                        blank=True,
                        help_text="SNOMED CT code (may have 'b' prefix)",
                        max_length=50,
                    ),
                ),
                (
                    "clean_snomed_ct_concept_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SNOMED code with 'b' prefix removed",
                        max_length=50,
                    ),
                ),
                (
                    "most_recent_release_year",
                    models.IntegerField(help_text="Most recent release year"),
                ),
                ("emis_code_cat_id", models.IntegerField(help_text="EMIS category ID")),
                (
                    "emis_cat_description",
                    models.CharField(
                        help_text="EMIS category description", max_length=200
                    ),
                ),
                (
                    "parent_category",
                    models.CharField(help_text="Parent category", max_length=200),
                ),
                (
                    "is_negated",
                    models.BooleanField(
                        default=False, help_text="Is this a negated term"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, help_text="Is this a resolved condition"
                    ),
                ),
                (
                    "is_historical",
                    models.BooleanField(default=False, help_text="Is this historical"),
                ),
                (
                    "is_familial",
                    models.BooleanField(
                        default=False, help_text="Is this family history"
                    ),
                ),
                (
                    "is_genetic_risk",
                    models.BooleanField(
                        default=False, help_text="Is this genetic risk"
                    ),
                ),
                (
                    "is_screening",
                    models.BooleanField(default=False, help_text="Is this screening"),
                ),
                (
                    "is_monitoring",
                    models.BooleanField(default=False, help_text="Is this monitoring"),
                ),
                (
                    "is_administrative",
                    models.BooleanField(
                        default=False, help_text="Is this administrative"
                    ),
                ),
                (
                    "is_education",
                    models.BooleanField(default=False, help_text="Is this education"),
                ),
                (
                    "is_referral",
                    models.BooleanField(default=False, help_text="Is this referral"),
                ),
                (
                    "is_test_request",
                    models.BooleanField(
                        default=False, help_text="Is this test request"
                    ),
                ),
                (
                    "is_symptom",
                    models.BooleanField(default=False, help_text="Is this symptom"),
                ),
                (
                    "is_exclusion",
                    models.BooleanField(default=False, help_text="Is this exclusion"),
                ),
                (
                    "is_qualifier",
                    models.BooleanField(default=False, help_text="Is this qualifier"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["clean_med_code_id"],
                        name="core_emisco_clean_m_cd0d87_idx",
                    ),
                    models.Index(
                        fields=["clean_snomed_ct_concept_id"],
                        name="core_emisco_clean_s_683254_idx",
                    ),
                    models.Index(
                        fields=["parent_category"],
                        name="core_emisco_parent__1fc9e4_idx",
                    ),
                    models.Index(
                        fields=["emis_cat_description"],
                        name="core_emisco_emis_ca_0609e2_idx",
                    ),
                    models.Index(fields=["term"], name="core_emisco_term_798f01_idx"),
                ],
            },
        ),
    ]
